# -*- coding: utf-8 -*-
"""Modelo_1er parcial_Com_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gPuz51o_4iyOqCUkTAm7MVOMyv2m8Xq6

# ![alt text](https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg)  **Modelo Primer parcial** ![alt text](https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg)



### Daniel: **daniel.alvarez@unahur.edu.ar**

### **Ejercicio 1**

Escribir la función recursiva **tieneRepetidos(vector)**, que retorna True si vector tiene al menos un elemento repetido y False en caso contrario. Las soluciones que NO sean recursivas no serán tomadas en cuenta.

Por ejemplo:

Si arr1 = [5, 10, 9, 8, 13, 21] y arr2 = [3, 13, 8, 9, 8, 5]

=> **tieneRepetidos(arr1)** devuelve False y **tieneRepetidos(arr2)** devuelve True

Ayuda: Pueden pensar en escribir una función que busque un elemento dentro de un vector. Al menos una de las funciones implementadas debe ser recursiva (principal o auxiliares).
"""



"""### **Ejercicio 2**

El gobierno nacional decidió llevar adelante un plan de granjas de agricultura agroecológica para garantizar la soberanía alimentaria de la población. Para eso nos pide desarrollar un software para diseñar la distribución de las plantas en los bancales.

Una planta se define con:

- Un nombre
- Un tipo: “hoja” o “fruto”
- Una fecha de siembra (para simplificar la modelamos como **int**).

Las plantas en los bancales se distribuyen en hileras (filas) de plantas, donde todas las hileras tienen la misma cantidad. Para ubicar las plantas tenemos la condición que dentro de la misma hilera no puede haber dos plantas seguidas del mismo tipo (“hoja” o “fruto”) para garantizar el cuidado del agrosistema. Notar que la condición solo aplica entre las plantas que forman parte de una misma hilera (fila) pero no hay ninguna restricción entre las plantas en una hilera y las de sus hileras vecinas.

Implementar el TDA **Bancal** que contenga al menos las siguientes operaciones:

-  **__init__(cantHileras, cantPlantasPorHilera):** que recibe el tamaño del bancal.

- **ubicarPlanta(nombrePlanta, tipoPlanta, fechaSiembra)**: que recibe los datos de la planta y la ubica en el bancal retornando la posición (fila y columna). Si la planta no puede ser ubicada por alguna razón, se debe lanzar una excepción. Recordar que no pueden ir dos plantas del mismo tipo seguidas en la misma fila.

- **cosecharPlanta(fechaActual):** que recibe la fecha actual (int), saca del bancal y retorna la primera planta que encuentre que haya sido plantada hace 20 días o más. Si no hay ninguna planta para cosechar se debe retornar None.

- **__repr__():** que muestra la distribución de las plantas en el bancal.

Ayuda:  Implementar primero el TDA Planta.

####Notas:


- No son las únicas operaciones necesarias, agregar las operaciones y funciones que consideren necesarias.
-  Una bancal vacio contiene None o cero en todas las posiciones.
- Los bancales tienen siempre 2 o más plantas por hilera


"""

